language: elixir

elixir:
  - 1.4.0

otp_release:
  - 19.2

dist: trusty

addons:
  postgresql: "9.6"

services:
  - postgresql

cache:
  directories:
    - _build
    - deps

env:
  - MIX_ENV=test

before_script:
  - mix ecto.create
  - mix ecto.migrate

script:
  - mix credo
  - mix test
